### ISSUE TITLE
I keep have apktool error with a specific APK file

### ISSUE THREAD

**Issue by youngexplorer** [kefir500/apk-icon-editor#19]
I try to edit an APK but it keep giving apktool error. I post here the log. In this log, I opened 2 apk, the one with error I opened twice. I don't know what else to do.

[12:46:02] APK Icon Editor v1.2.0 
[12:46:02] Initializing... 
[12:46:02] "JRE" 32-bit found: 
[12:46:02] "java version "1.8.0_31"

Java(TM) SE Runtime Environment (build 1.8.0_31-b13)

Java HotSpot(TM) Client VM (build 25.31-b07, mixed mode, sharing)" 
[12:46:02] "JDK" 32-bit not found! 
[12:46:02] Language set to "en" 
[12:46:03] Starting...
 
[12:46:23] Unpacking "C:/Users/DodobeKimkim/Dropbox/Tu vi 2015/APK/VA 1.0.6 GGGG tuvi2015.apk" 
[12:46:23] aapt exit code: 0 
[12:46:32] Unpacked in 7.994s 
[12:46:32] "W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff

Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f

	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)

	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:59)

	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:55)

	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:35)

	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:351)

	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)

	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)

	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)

	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:87)

	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:146)

	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)

	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:107)

	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)

	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:304)

	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:116)

	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)

	at brut.apktool.Main.cmdDecode(Main.java:169)

	at brut.apktool.Main.main(Main.java:85)

" 
[12:46:32] Error (Apktool Error): Apktool Error 
[12:47:30] Unpacking "C:\Users\DodobeKimkim\Dropbox\FootballQuiz\apk\Google play\FootballQuiz_G.2.0.1.apk" 
[12:47:30] aapt exit code: 0 
[12:47:45] Unpacked in 13.646s 
[12:47:45] Icons: ("res/drawable-ldpi/ic_launcher.png", "res/drawable-mdpi/ic_launcher.png", "res/drawable-hdpi/ic_launcher.png", "res/drawable-xhdpi/ic_launcher.png", "res/drawable-xxhdpi/ic_launcher.png", "") 
[12:47:45] Done.
 
[12:52:03] Unpacking "C:/Users/DodobeKimkim/Dropbox/Tu vi 2015/APK/VA 1.0.6_GGGG_tuvi2015.apk" 
[12:52:03] aapt exit code: 0 
[12:52:13] Unpacked in 9.114s 
[12:52:13] "W: Could not decode attr value, using undecoded value instead: ns=android, name=touchscreenBlocksFocus, value=0xffffffff
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x0101048f
	at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:59)
	at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:55)
	at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:35)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:351)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:87)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:146)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:107)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:91)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:304)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:116)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:114)
	at brut.apktool.Main.cmdDecode(Main.java:169)
	at brut.apktool.Main.main(Main.java:85)

" 
[12:52:13] Error (Apktool Error): Apktool Error

**Comment by kefir500** [comment]
What is the original application name of this APK?

**Comment by youngexplorer** [comment]
If by original APK name you mean the name used before using APK Icon editor is "VA 1.0.6 GGGG tuvi2015.apk"

**Comment by kefir500** [comment]
No, I mean the name of the application itself (e.g. "Google Drive", "Angry Birds Space", "VLC Media Player", etc.). I'm trying to find this APK to test it. Or you could just send the link to it.

**Comment by youngexplorer** [comment]
Here is the link to download. 
http://www.mediafire.com/download/9d0v259te5m881k/VA_1.0.6_GGGG_tuvi2015.apk

**Comment by kefir500** [comment]
**Step 1: Unpacking the APK using "Apktool RC3"**
This APK can be handled using Apktool RC3/RC4. The newest (v1.2.0) Apk Icon Editor version uses Apktool RC2, while v1.1.1 uses RC3.
* Downgrade to [APK Icon Editor v1.1.1](https://github.com/kefir500/apk-icon-editor/releases/tag/v1.1.1);
* Open your APK with it.

**Step 2: Packing the APK**
This APK contains an invalid PNG file, that is why we will have to fix it:
* *"File"* --> *"Explore APK Contents"* (or simply press **Ctrl+D**);
* Open **"res\drawable-hdpi"** folder;
* Find the PNG named **"option_aicap_active.png"**;
* Replace it with any other *valid* PNG;
* Pack your APK.

Let me know if these steps helped you or not.

**Comment by youngexplorer** [comment]
It worked. I replaced the defective PNG. One more question. Can I repackage the APK with my key to sign it? In 1.2.0 has that functionality.

**Comment by kefir500** [comment]
For now I can only suggest you the following:
Copy **"apktool.jar"** from v1.1.1 and paste it to v1.2.0.
This will do the trick: you will be able to use your own keys, as well as Apktool RC3.
Future "APK Icon Editor" releases will definitely include more stable Apktool versions.

**Comment by youngexplorer** [comment]
Thanks. Everything works
