### ISSUE TITLE
Invalid application version code

### ISSUE THREAD

**Issue by filmplus** [kefir500/apk-icon-editor#20]
Hi.
iv'e got error "Apktool error" when tried to pack my app after rename it.
and here is the log file error:

[13:46:29] APK Icon Editor v1.2.0 
[13:46:29] Initializing... 
[13:46:30] "JRE" 32-bit found: 
[13:46:30] "java version "1.8.0"

Java(TM) SE Runtime Environment (build 1.8.0-b132)

Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)" 
[13:46:30] "JDK" 32-bit not found! 
[13:46:30] Language set to "en" 
[13:46:31] Starting...
 
[13:46:39] Unpacking "C:/Users/Arizona/Desktop/FilmPlus-app.apk" 
[13:46:39] aapt exit code: 0 
[13:46:49] Unpacked in 9.135s 
[13:46:49] Icons: ("res/drawable-ldpi/ic_launcher.png", "res/drawable-mdpi/ic_launcher.png", "res/drawable-hdpi/ic_launcher.png", "res/drawable-xhdpi/ic_launcher.png", "", "") 
[13:46:49] Done.
 
[13:47:07] Packing APK... 
	Filename: "C:/Users/Arizona/Desktop/Film.apk" 
	Application name: "FilmPlus App" 
	Application version code: "۱" 
	Application version name: "1.0" 
	Using Apktool: true 
	Ratio: 9 
	Smali: false 
	Sign: true 
	Zipalign: true 
	Using KeyStore: false 
	PEM found; 
	PK8 found; 
	KeyStore NOT found; 
	KeyStore Password: NOT present; 
	Alias: "" 
	Alias Password: NOT present; 
[13:47:07] Resource values/strings.xml: app_name = 'FilmPlus App' 
[13:47:07] versionCode: "1" => "۱" 
[13:47:07] versionName: "1.0" => "1.0" 
[13:47:14] "C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml:2: error: Error: Resource id cannot be an empty string (at 'versionCode' with value '?').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_6511813877399214585.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ?, --version-name, 1.0, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL5359399058906033524.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:435)

	at brut.androlib.Androlib.buildResources(Androlib.java:363)

	at brut.androlib.Androlib.build(Androlib.java:286)

	at brut.androlib.Androlib.build(Androlib.java:258)

	at brut.apktool.Main.cmdBuild(Main.java:236)

	at brut.apktool.Main.main(Main.java:88)

Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_6511813877399214585.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ?, --version-name, 1.0, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL5359399058906033524.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:470)

	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:416)

	... 5 more

Caused by: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_6511813877399214585.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ?, --version-name, 1.0, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL5359399058906033524.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.util.OS.exec(OS.java:89)

	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:464)

	... 6 more

" 
[13:47:14] Error (Apktool Error): Apktool Error 
[13:49:48] Warning (): "Version Name" field cannot be empty. 
[13:50:01] Packing APK... 
	Filename: "C:/Users/Arizona/Desktop/App.apk" 
	Application name: "FilmPlus App" 
	Application version code: "۱" 
	Application version name: "1" 
	Using Apktool: true 
	Ratio: 9 
	Smali: false 
	Sign: true 
	Zipalign: true 
	Using KeyStore: false 
	PEM found; 
	PK8 found; 
	KeyStore NOT found; 
	KeyStore Password: NOT present; 
	Alias: "" 
	Alias Password: NOT present; 
[13:50:01] Resource values/strings.xml: app_name = 'FilmPlus App' 
[13:50:01] versionCode: "1" => "۱" 
[13:50:01] versionName: "1.0" => "1" 
[13:50:08] "C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml:2: error: Error: Resource id cannot be an empty string (at 'versionCode' with value '?').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_618316048121042722.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ?, --version-name, 1, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL9165742596759874107.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:435)

	at brut.androlib.Androlib.buildResources(Androlib.java:363)

	at brut.androlib.Androlib.build(Androlib.java:286)

	at brut.androlib.Androlib.build(Androlib.java:258)

	at brut.apktool.Main.cmdBuild(Main.java:236)

	at brut.apktool.Main.main(Main.java:88)

Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_618316048121042722.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ?, --version-name, 1, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL9165742596759874107.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:470)

	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:416)

	... 5 more

Caused by: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_618316048121042722.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ?, --version-name, 1, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL9165742596759874107.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.util.OS.exec(OS.java:89)

	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:464)

	... 6 more

" 
[13:50:08] Error (Apktool Error): Apktool Error 

please help me there.
Thanks.

**Comment by kefir500** [comment]
Hi. Seems that application **version code** is invalid.
Try to change it to numberical value (**10**, for example).

**Comment by filmplus** [comment]
Hi. thank you for reply.
i did but not working again!
here is the results:

[16:00:30] Initializing... 
[16:00:31] "JRE" 32-bit found: 
[16:00:31] "java version "1.8.0"

Java(TM) SE Runtime Environment (build 1.8.0-b132)

Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)" 
[16:00:31] "JDK" 32-bit not found! 
[16:00:31] Language set to "en" 
[16:00:32] Starting...
 
[16:00:36] Unpacking "C:/Users/Arizona/Desktop/TESTAPP.apk" 
[16:00:36] aapt exit code: 0 
[16:00:45] Unpacked in 8.333s 
[16:00:45] Icons: ("res/drawable-ldpi/ic_launcher.png", "res/drawable-mdpi/ic_launcher.png", "res/drawable-hdpi/ic_launcher.png", "res/drawable-xhdpi/ic_launcher.png", "", "") 
[16:00:45] Done.
 
[16:01:14] Packing APK... 
	Filename: "C:/Users/Arizona/Desktop/Test-Plus.apk" 
	Application name: "FilmPlus" 
	Application version code: "۱۱" 
	Application version name: "11" 
	Using Apktool: true 
	Ratio: 9 
	Smali: false 
	Sign: true 
	Zipalign: true 
	Using KeyStore: false 
	PEM found; 
	PK8 found; 
	KeyStore NOT found; 
	KeyStore Password: NOT present; 
	Alias: "" 
	Alias Password: NOT present; 
[16:01:14] Resource values/strings.xml: app_name = 'FilmPlus' 
[16:01:14] versionCode: "1" => "۱۱" 
[16:01:14] versionName: "1.0" => "11" 
[16:01:20] "C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml:2: error: Error: No resource found that matches the given name (at 'versionCode' with value '??').

Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_5841037062411234861.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ??, --version-name, 11, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL8562864509166682789.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:435)

	at brut.androlib.Androlib.buildResources(Androlib.java:363)

	at brut.androlib.Androlib.build(Androlib.java:286)

	at brut.androlib.Androlib.build(Androlib.java:258)

	at brut.apktool.Main.cmdBuild(Main.java:236)

	at brut.apktool.Main.main(Main.java:88)

Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_5841037062411234861.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ??, --version-name, 11, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL8562864509166682789.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:470)

	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:416)

	... 5 more

Caused by: brut.common.BrutException: could not exec command: [C:\Users\Arizona\AppData\Local\Temp\brut_util_Jar_5841037062411234861.tmp, p, --forced-package-id, 127, --min-sdk-version, 9, --target-sdk-version, 17, --version-code, ??, --version-name, 11, -F, C:\Users\Arizona\AppData\Local\Temp\APKTOOL8562864509166682789.tmp, -I, C:\Users\Arizona\apktool\framework\1.apk, -S, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\res, -M, C:\Users\Arizona\AppData\Local\Temp\apk-icon-editor\apk\AndroidManifest.xml]

	at brut.util.OS.exec(OS.java:89)

	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:464)

	... 6 more

" 
[16:01:20] Error (Apktool Error): Apktool Error

**Comment by filmplus** [comment]
may i send my apk for you to open it in your local tool?

**Comment by kefir500** [comment]
Of course. Send your APK [here](mailto:kefir500@gmail.com).

**Comment by filmplus** [comment]
i left a message for you and attached the app.
please check.
thank you

**Comment by kefir500** [comment]
I'm not sure why the invalid version code is shown on your machine.
Try deleting **1.apk**  located at **C:\Users\%USERNAME%\apktool\framework**.
Anyway, I've attached the repacked APK for you, check your email.

**Comment by filmplus** [comment]
Yes! i don't know how to say thank you bro.
iv'e got the new apk and it's working like a charm, and fully renamed.
cheers
