### ISSUE TITLE
Singed apk issue on iMac 

### ISSUE THREAD

**Issue by bugatsinho** [kefir500/apk-icon-editor#86]
After installing Android Studio in my iMac and download and install all the necessary files as I saw in a course, I'm having this issue when I'm using APK icon editor app!
![image](https://user-images.githubusercontent.com/18536253/67446844-89c9fa80-f5d7-11e9-9dee-7b3c97ba60a5.png)

> ----- APK not signed -----
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at com.android.signapk.SignApk.addDigestsToManifest(SignApk.java:169)
	at com.android.signapk.SignApk.main(SignApk.java:325)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
![image](https://user-images.githubusercontent.com/18536253/67447166-a286e000-f5d8-11e9-9144-61c084be5994.png)

any ideas or solutions?

**Comment by kefir500** [comment]
`Signapk` should work with Java 8.
Seems that APK Icon Editor is using Java > 8 (this can be checked in **Help** --> **About** section), however the auto-detection of a signing tool is picking up Java 8 from the environment variables.

Try switching to `Apksigner` in **Settings** --> **Repacking** dialog.

**Comment by bugatsinho** [comment]
Switching to Apksigner in Settings did the trick!!
I'm feeling like a noob! I didn't think to check on settings! 
Thank you so much!
